name = "CategoricalDistributions"
uuid = "af321ab8-2d2e-40a6-b165-3d674595d28e"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>"]
version = "0.1.15"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ScientificTypes = "321657f4-b219-11e9-178b-2701a2544e81"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[weakdeps]
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[extensions]
UnivariateFiniteDisplayExt = "UnicodePlots"

[compat]
BenchmarkTools = "1.3.2"
CategoricalArrays = "0.9, 0.10"
Distributions = "0.25"
Missings = "0.4, 1"
OrderedCollections = "1.1"
ScientificTypes = "3.0"
UnicodePlots = "2, 3"
julia = "1.6"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[targets]
test = ["BenchmarkTools", "FillArrays", "Random", "StableRNGs", "Test", "UnicodePlots"]
